
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: k8s-cluster-shadab.groveops.net 
    node-group: amd
    name: amd-node-group
  name: amd-nodes-us-west-2b
spec:
  nodeLabels:
    name: amd-node-group
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20230207
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: required
  machineType: t3a.medium
  maxSize: 1
  minSize: 1
  role: Node
  subnets:
  - us-west-2b