# api Version: v1
# kind: Namespace
# metadata:
#   name: arm-namespace
# ---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: kops-shadab.groveops.net 
    node-group: graviton
    name: arm-node-group
  name: graviton-nodes-us-west-2a
spec:
  nodeLabels:
    name: arm-node-group
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-arm64-server-20230112
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: required
  machineType: m6g.medium
  maxSize: 1
  minSize: 1
  role: Node
  subnets:
  - us-west-2a
  rootVolumeSize: 50
  rootVolumeType: gp2