apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: kops.example.com
    node-group: graviton
    name: arm-node-group
  name: graviton-nodes-us-east-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-arm64-server-20230112
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: required
  machineType: m6g.medium
  maxSize: 1
  minSize: 1
  role: Node
  subnets:
  - us-east-1a
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: kops.example.com
    node-group: amd
    name: amd-node-group
  name: amd-nodes-us-east-1b
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20230207
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: required
  machineType: t3a.medium
  maxSize: 1
  minSize: 1
  role: Node
  subnets:
  - us-east-1b