apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino-deployment-amd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trino-amd
  template:
    metadata:
      labels:
        app: trino-amd
    spec:
      nodeSelector:
        name: amd-node-group
      containers:
      - name: trino-amd-container
        image: lewuathe/trino-worker:354
        env:
          - name: discovery_uri
            value: trino-coordinator.default.svc.cluster.local
        command: ["/bin/sh", "-c"]
        args:
          - "./scripts/trino.sh http://$discovery_uri:8080 "