apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
    # service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  name: trino-coordinator
spec:
  ports:
    - name: client
      port: 8080
  type: LoadBalancer
  selector:
    app: trino-coordinator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino-coordinator
  labels:
    app: trino-coordinator
spec:
  selector:
    matchLabels:
      app: trino-coordinator
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 100%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: trino-coordinator
      annotations:
         cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    spec:
      nodeSelector:
        name: amd-node-group
      containers:
        - name: trino-arm-container
          image: lewuathe/trino-coordinator:354
          ports:
            - containerPort: 8080
          env:
            - name: discovery_uri
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: node_id
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          command: ["/bin/sh", "-c"]
          args:
            - "./scripts/trino.sh http://$discovery_uri:8080 $node_id"