apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino-deployment-arm
  namespace: arm-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: trino-arm
  template:
    metadata:
      labels:
        app: trino-arm
    spec:
      nodeSelector:
        name: arm-node-group
      containers:
      - name: trino-arm-container
        image: lewuathe/trino-worker:354-arm64v8
        env:
          - name: discovery_uri
            value: trino-coordinator.default.svc.cluster.local
          - name: node_id
            valueFrom:
              fieldRef:
                fieldPath:   metadata.name
        command: ["/bin/sh", "-c"]
        args:
          - "./scripts/trino.sh http://$discovery_uri:8080 $node_id"